name: Update GitHub Trophy

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Trophy
        run: |
          mkdir -p profile
          curl -L "https://github-profile-trophy.vercel.app/?username=bhargav7655&theme=darkhub&no-frame=true&no-bg=true&margin-w=15" \
            -o profile/trophy.svg

      - name: Commit trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/trophy.svg
          git commit -m "Update GitHub trophy" || exit 0
          git push
